import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });
// const quiksand=Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider clientId="901864704419-bs8jk6e8t46l6scs17s26q04365q82s8.apps.googleusercontent.com">

    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </GoogleOAuthProvider>
  );
}
